# Generated by Django 2.1.2 on 2018-10-15 17:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='SOME STRING', max_length=200)),
                ('quota', models.TextField(default='SOME STRING', max_length=5000)),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('background', models.FileField(blank=True, max_length=1000, null=True, upload_to='items/%Y/%m/%d')),
                ('movie_image', models.FileField(blank=True, max_length=1000, null=True, upload_to='items/%Y/%m/%d')),
                ('movie_image_b', models.FileField(blank=True, max_length=1000, null=True, upload_to='items/%Y/%m/%d')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
