# Generated by Django 2.1.2 on 2018-10-17 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='quota',
            field=models.TextField(default='text', max_length=5000),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(default='text'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(default='text', max_length=200),
        ),
    ]
