# Generated by Django 2.1.2 on 2018-10-29 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20181028_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='rating_average',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
