# Generated by Django 2.1.2 on 2018-11-09 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_remove_post_rating_average'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(blank=True, default=3, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Post'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='rating',
            field=models.IntegerField(choices=[(1, 'one'), (2, 'two'), (3, 'three'), (4, 'four'), (5, 'five')], default=3, verbose_name='Rating (stars)'),
        ),
        migrations.AlterField(
            model_name='post',
            name='background',
            field=models.FileField(default='empty', max_length=1000, upload_to='items/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='post',
            name='movie_image',
            field=models.FileField(blank=True, default='empty', max_length=1000, null=True, upload_to='items/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='post',
            name='movie_image_b',
            field=models.FileField(blank=True, default='empty', max_length=1000, null=True, upload_to='items/%Y/%m/%d'),
        ),
    ]
